### ISSUE TITLE
get value at drag/scrub end

### ISSUE THREAD

**Issue by tconroy** [desmosinc/scrubber#14]
Hey there!

Great plugin. I was curious if you knew how I could accomplish a particular feature ( or if you'd be interested in building it in to the plugin ). I'd like a callback for when the user has stopped scrubbing. We current have the `onValueChange` method which is great for updating at each step, but I have a processing-intensive task I'd like to trigger only when the user has let go of the scrubber / stopped scrubbing. 

Currently I'm trying to add events via jQuery,

```
$(scrubber.elt).find('.track, .thumb').on('dragend mouseup click', () => {
  console.log('scrubber released');
});
```

.. which seems to work well for desktop but not at all for mobile.

Any input much appreciated. :)

**Comment by jwmerrill** [comment]
This sounds like a reasonable feature to add. Would you be interested in contributing it? Here are the steps I see:

* Add empty `onScrubStart` and `onScrubEnd` functions in the [constructor](https://github.com/desmosinc/scrubber/blob/fcf4b39df055befaa83d19bb1a7d7b2456a0077c/scrubber.js#L1-L6).
* Call `self.onScrubStart()` somewhere inside the [start function](https://github.com/desmosinc/scrubber/blob/fcf4b39df055befaa83d19bb1a7d7b2456a0077c/scrubber.js#L109).
* Call `self.onScrubEnd()` somewhere inside the [stop function](https://github.com/desmosinc/scrubber/blob/fcf4b39df055befaa83d19bb1a7d7b2456a0077c/scrubber.js#L129).
* Add documentation for the new callbacks.

**Comment by tconroy** [comment]
Hi @jwmerrill,
Happily! I've opened a PR over at #15. 

I'm also currently porting your code over to ES6 classes / module structure. Please let me know if this is something you'd be interested in as well. 

Cheers!

**Comment by jwmerrill** [comment]
Re: ES6 classes / module, I would prefer not to go that direction at this time, because I don't want to add a build step to this repo.
